#include "includes.h"
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
BOOL APIENTRY DllMain(HMODULE module, DWORD reason, LPVOID reserved) {
	if (reason == DLL_PROCESS_ATTACH) {
		novacane::init();
	}

	return TRUE;
}
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS
// GO TO sdk.h TO UPDATE THE OFFSETS